import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/pages/Reusable/Header/Header";
import Footer from "@/components/pages/Reusable/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Subhro Mondal",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
          {children}
        <Footer/>
        </body>
    </html>
  );
}
